apiVersion: v1  
kind: Service  
metadata:  
  name: {{ include "cursus.fullname" . }}  
  labels:
    {{- include "cursus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}  
  ports:  
    - port: {{ .Values.service.port }}  
      targetPort: broker  
      protocol: TCP  
      name: broker  
  selector:  
     {{- include "cursus.selectorLabels" . | nindent 4 }}