name: GoSec Security Analysis

on:
  push:
    branches: [main, release-*]
    paths:
      - '.github/workflows/**'
      - 'go.mod'
      - 'go.sum'
      - 'broker.go'
      - 'cmd/**'
      - 'pkg/**'
      - 'sdk/**'
      - 'util/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'go.mod'
      - 'go.sum'
      - 'broker.go'
      - 'cmd/**'
      - 'pkg/**'
      - 'sdk/**'
      - 'util/**'

jobs:
  gosec:
    name: 🔒 GoSec Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run GoSec
        uses: securego/gosec@v2.22.4
        with:
          args: '-no-fail -fmt sarif -out gosec-results.sarif ./...'

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gosec-results.sarif
